Adding kafka producer error metrics to logger
ess-dmsc/forwarder pull request #85
Opened 2021-02-25 10:26 UTC by kmurica

2021-02-25 10:27 UTC, kmurica commented
@matthew-d-jones Something like this? Corresponding Jira ticket:
https://jira.esss.lu.se/browse/ECDC-2317

2021-02-26 08:52 UTC, ebadkamil commented on forwarder/kafka/kafka_producer.py
> +            self.logger.error(
May be combine this info in the previous log message. I am not sure.  What do you think?

2021-02-26 09:06 UTC, matthew-d-jones requested changes
Sorry I meant tracking with a counter that gets reported to graphite using what Ebad has implemented: https://github.com/ess-dmsc/forwarder/pull/82. It would allow us to track this error on a grafana dashboard.
It would also give us the option of not sending the log message altogether. My concern is that if we hit this error it could trigger at the rate we produce messages from the Forwarder (up to ~10,000 per second) and effectively mount a DoS attack on our logging server. The periodic reporting of the counter as a metric gets around this problem. We take a similar approach for errors which can be very frequent in the Filewriter.

2021-03-03 07:52 UTC, matthew-d-jones requested changes
Implementation looks good, but I think the severity is now not clear. `BufferError` specifically means the buffer is full, I wish it was called `FullBufferError`...
It is important that it is understood that this is a critical problem and that data is being lost. Could you use the original error log string as a comment where the `BufferError` is caught, and report the error to graphite as `data_loss_errors`?
```
                "Producer message buffer is full. "
                self._update_buffer_err_counter.increment()
                "Data loss occurred as messages are produced "
                f"faster than are sent to the kafka broker: {e}"
```

2021-03-03 09:41 UTC, matthew-d-jones approved these changes
Thanks, LGTM

2021-03-03 09:54 UTC, kmurica commented
@ebadkamil does it look good to you? If so, could you merge the PR to main?

2021-03-03 10:02 UTC, ebadkamil commented
yes Thanks. LGTM.

2021-03-03 10:07 UTC, merged